# Generated by Django 5.2 on 2025-05-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Укажите название фильма')),
                ('relase_date', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(default='фантастика', max_length=255, verbose_name='Укажите жанр')),
                ('author', models.CharField(max_length=255, verbose_name='Укажите автора')),
                ('description', models.TextField(verbose_name='Укажите описание фильма')),
                ('trailer_url', models.URLField(blank=True, null=True, verbose_name='Вставьте ссылку фильма')),
            ],
        ),
    ]
